# Generated by Django 6.0.3 on 2026-04-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dishes',
            field=models.ManyToManyField(blank=True, related_name='related_dishes', to='booking.dish'),
        ),
        migrations.AddField(
            model_name='dish',
            name='items',
            field=models.ManyToManyField(related_name='bookings', to='booking.dish'),
        ),
    ]
