# Generated by Django 6.0.3 on 2026-06-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(default='18:00', help_text='Choose a reservation time'),
            preserve_default=False,
        ),
    ]
