# Generated by Django 6.0.3 on 2026-09-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(help_text='Choose a reservation date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_count',
            field=models.PositiveIntegerField(help_text='Number of guests'),
        ),
    ]
